### PR TITLE
unable to load quote after order is placed

### PR DESCRIPTION
**Pull request by yaroslav-qlicks**
### Description (*)
unable to load quote after order is placed

### Fixed Issues (if relevant)
https://github.com/mageplaza/magento-2-smtp/issues/315

1. Fixes mageplaza/magento-2-smtp#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### CODE REVIEW

**Comment by yaroslav-qlicks** [comment]
@Victor-Mageplaza @haitv282 could you check please and merge?

**Comment by template-provider** [comment]
+1 for merge .... huge problem

**Comment by phes71** [comment]
this is also an issue with swissup fire checkout

**Comment by DanielRuf** [comment]
Bump @Victor-Mageplaza

Until this is released as new patch release we will have to patch it with composer-patches.

**Comment by jg-development** [comment]
@Victor-Mageplaza 
Can this be merged?

**Comment by jonkeren** [comment]
Please merge this one. Thanks.

**Comment by DanielRuf** [comment]
cc @haitv282

**Comment by KhietNguyen83** [comment]
Thank you for your contribution.
I have merged your patch and will release it soon.
Thank you!

**Pull request merged**
