### PR TITLE
fix sending mails with amazon ses smtp for magento 2.3.3

### PR DESCRIPTION
**Pull request by taoufiqaitali**
issue when sending mail with amazon ses smtp

**Expect**
send mail
**Result**
Transaction failed: Expected disposition, got =

**fix issue**
#199

### CODE REVIEW

**Comment by Arthas7895** [comment]
I will check your PR on my site and inform you soon

**Comment by marcinsdance** [comment]
This pull request also fixes this issue for Magento v.2.2.10 - if you change:
`if ($this->helper->versionCompare('2.3.3')) {`
to:
`if ($this->helper->versionCompare('2.2.10')) {`

**Comment by dbashyal** [comment]
Is anyone going to approve this pull? I'm getting same error as well.

**Comment by ronn0** [comment]
Please merge this PR. And do it for 2.2.10 too.

**Comment by Arthas7895** [comment]
Thank you @taoufiqaitali again. I will continue to fix it to be compatible with both Magento versions 2.2.10

**Comment by dragonfly4** [comment]
@Arthas7895 can you release this fix as a proper release please? Also having issues with SES and composer is loading the version from November 4th.

**Pull request merged**
