### PR TITLE
Fix accents in str

### PR DESCRIPTION
**Pull request by TonySma**

### CODE REVIEW

**Comment by Arthas78** [comment]
I answered you in the issue #139 so I will close this issue here
Thank you very much!

**Comment by TonySma** [comment]
Hello, 
Can you accept the merge ? 

Tony

**Comment by Arthas78** [comment]
Due to that problem, only a few new sites appear so we will note and consider it in the next updates.

**Comment by Arthas78** [comment]
I will close the issue here. Thank you again!

**Pull request closed without merging**
