### PR TITLE
Update TransportBuilder.php

### PR DESCRIPTION
**Pull request by SamB-GB**
From "Rewrite" improvements.
+ also includes compatibility for Mirasvit Follow Up E-mail

### CODE REVIEW

**Comment by SamB-GB** [comment]
Related to

https://github.com/mageplaza/magento-2-smtp/issues/188

**Comment by Arthas7895** [comment]
After updating SMTP to be compatible with Magento version 2.2.8 and above, we have encountered quite a few cases with Mirasvit Follow up email. and we edited the code so that they are compatible with Mirasvit's side. It's fun when we have the same solution. We will update it in the next SMTP version.
Thank you very much for your contribution to the improved extension

**Comment by Arthas7895** [comment]
Since this is a compatibility issue between the two modules, we are not sure if these updates can still work in new versions, so I will only note them but not added in the official version. Thank you very much for contributing to the module

**Comment by SamB-GB** [comment]
This works fine on Magento 2.3.2 which is the latest version. All order e-mails, shipping e-mails etc go out as normal

**Pull request closed without merging**
